// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger-service.proto

package pplogger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorMessage_Severity int32

const (
	ErrorMessage_FATAL   ErrorMessage_Severity = 0
	ErrorMessage_SEVERE  ErrorMessage_Severity = 1
	ErrorMessage_WARNING ErrorMessage_Severity = 2
)

var ErrorMessage_Severity_name = map[int32]string{
	0: "FATAL",
	1: "SEVERE",
	2: "WARNING",
}

var ErrorMessage_Severity_value = map[string]int32{
	"FATAL":   0,
	"SEVERE":  1,
	"WARNING": 2,
}

func (x ErrorMessage_Severity) String() string {
	return proto.EnumName(ErrorMessage_Severity_name, int32(x))
}

func (ErrorMessage_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{0, 0}
}

type ErrorMessage struct {
	Service              string                `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Function             string                `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Severity             ErrorMessage_Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=pplogger.ErrorMessage_Severity" json:"severity,omitempty"`
	Message              string                `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ErrorMessage) Reset()         { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()    {}
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{0}
}

func (m *ErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMessage.Unmarshal(m, b)
}
func (m *ErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMessage.Marshal(b, m, deterministic)
}
func (m *ErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMessage.Merge(m, src)
}
func (m *ErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ErrorMessage.Size(m)
}
func (m *ErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMessage proto.InternalMessageInfo

func (m *ErrorMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ErrorMessage) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *ErrorMessage) GetSeverity() ErrorMessage_Severity {
	if m != nil {
		return m.Severity
	}
	return ErrorMessage_FATAL
}

func (m *ErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterEnum("pplogger.ErrorMessage_Severity", ErrorMessage_Severity_name, ErrorMessage_Severity_value)
	proto.RegisterType((*ErrorMessage)(nil), "pplogger.ErrorMessage")
	proto.RegisterType((*Response)(nil), "pplogger.Response")
}

func init() { proto.RegisterFile("logger-service.proto", fileDescriptor_1484f153346fa394) }

var fileDescriptor_1484f153346fa394 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xeb, 0x42, 0x5b, 0xf7, 0xf8, 0xa3, 0xe8, 0x54, 0x21, 0xab, 0x0b, 0x51, 0xa6, 0x2e,
	0x78, 0x28, 0x0b, 0x12, 0x53, 0x86, 0x80, 0x2a, 0x85, 0x0e, 0x0e, 0x82, 0x19, 0xaa, 0x23, 0x8a,
	0x54, 0x62, 0xeb, 0x1c, 0x2a, 0xf5, 0x33, 0xf2, 0xa5, 0x10, 0x89, 0x53, 0x18, 0x3a, 0xfe, 0xee,
	0x9e, 0xef, 0xbd, 0x67, 0x98, 0x6d, 0x6d, 0x59, 0x12, 0xdf, 0x78, 0xe2, 0x5d, 0xb5, 0x21, 0xed,
	0xd8, 0x36, 0x16, 0xa5, 0x73, 0xdd, 0x3c, 0xf9, 0x16, 0x70, 0x9e, 0x31, 0x5b, 0x7e, 0x22, 0xef,
	0xdf, 0x4a, 0x42, 0x05, 0x93, 0xa0, 0x55, 0x22, 0x16, 0x8b, 0xa9, 0xe9, 0x11, 0xe7, 0x20, 0x3f,
	0xbe, 0xea, 0x4d, 0x53, 0xd9, 0x5a, 0x0d, 0xdb, 0xd5, 0x81, 0xf1, 0x1e, 0xa4, 0xa7, 0x1d, 0x71,
	0xd5, 0xec, 0xd5, 0x49, 0x2c, 0x16, 0x97, 0xcb, 0x6b, 0xdd, 0x7b, 0xe8, 0xff, 0xf7, 0x75, 0x11,
	0x64, 0xe6, 0xf0, 0xe0, 0xd7, 0xf2, 0xb3, 0xdb, 0xaa, 0xd3, 0xce, 0x32, 0x60, 0xa2, 0x41, 0xf6,
	0x7a, 0x9c, 0xc2, 0xe8, 0x21, 0x7d, 0x4e, 0xf3, 0x68, 0x80, 0x00, 0xe3, 0x22, 0x7b, 0xc9, 0x4c,
	0x16, 0x09, 0x3c, 0x83, 0xc9, 0x6b, 0x6a, 0xd6, 0xab, 0xf5, 0x63, 0x34, 0x4c, 0x62, 0x90, 0x86,
	0xbc, 0xb3, 0xb5, 0x27, 0x9c, 0xc1, 0x88, 0xc9, 0x6d, 0xf7, 0xa1, 0x46, 0x07, 0xcb, 0x15, 0x5c,
	0xe4, 0x6d, 0xaa, 0x22, 0xb4, 0xba, 0x03, 0x99, 0xdb, 0xb2, 0x8d, 0x88, 0x57, 0xc7, 0x33, 0xcf,
	0xf1, 0x6f, 0xde, 0x9f, 0x4f, 0x06, 0xef, 0xe3, 0xf6, 0x2f, 0x6f, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xec, 0x4a, 0x4a, 0x0e, 0x63, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerServiceClient is the client API for LoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerServiceClient interface {
	LogError(ctx context.Context, in *ErrorMessage, opts ...grpc.CallOption) (*Response, error)
}

type loggerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggerServiceClient(cc *grpc.ClientConn) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) LogError(ctx context.Context, in *ErrorMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pplogger.LoggerService/LogError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServiceServer is the server API for LoggerService service.
type LoggerServiceServer interface {
	LogError(context.Context, *ErrorMessage) (*Response, error)
}

// UnimplementedLoggerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServiceServer struct {
}

func (*UnimplementedLoggerServiceServer) LogError(ctx context.Context, req *ErrorMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogError not implemented")
}

func RegisterLoggerServiceServer(s *grpc.Server, srv LoggerServiceServer) {
	s.RegisterService(&_LoggerService_serviceDesc, srv)
}

func _LoggerService_LogError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).LogError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pplogger.LoggerService/LogError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).LogError(ctx, req.(*ErrorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pplogger.LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogError",
			Handler:    _LoggerService_LogError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger-service.proto",
}
