// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger-service.proto

package pplogger

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorMesage_Severity int32

const (
	ErrorMesage_FATAL   ErrorMesage_Severity = 0
	ErrorMesage_SEVERE  ErrorMesage_Severity = 1
	ErrorMesage_WARNING ErrorMesage_Severity = 2
)

var ErrorMesage_Severity_name = map[int32]string{
	0: "FATAL",
	1: "SEVERE",
	2: "WARNING",
}

var ErrorMesage_Severity_value = map[string]int32{
	"FATAL":   0,
	"SEVERE":  1,
	"WARNING": 2,
}

func (x ErrorMesage_Severity) String() string {
	return proto.EnumName(ErrorMesage_Severity_name, int32(x))
}

func (ErrorMesage_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{0, 0}
}

type ErrorMesage struct {
	Service              string               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Function             string               `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	Severity             ErrorMesage_Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=pplogger.ErrorMesage_Severity" json:"severity,omitempty"`
	Message              string               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ErrorMesage) Reset()         { *m = ErrorMesage{} }
func (m *ErrorMesage) String() string { return proto.CompactTextString(m) }
func (*ErrorMesage) ProtoMessage()    {}
func (*ErrorMesage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{0}
}

func (m *ErrorMesage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMesage.Unmarshal(m, b)
}
func (m *ErrorMesage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMesage.Marshal(b, m, deterministic)
}
func (m *ErrorMesage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMesage.Merge(m, src)
}
func (m *ErrorMesage) XXX_Size() int {
	return xxx_messageInfo_ErrorMesage.Size(m)
}
func (m *ErrorMesage) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMesage.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMesage proto.InternalMessageInfo

func (m *ErrorMesage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ErrorMesage) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *ErrorMesage) GetSeverity() ErrorMesage_Severity {
	if m != nil {
		return m.Severity
	}
	return ErrorMesage_FATAL
}

func (m *ErrorMesage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1484f153346fa394, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterEnum("pplogger.ErrorMesage_Severity", ErrorMesage_Severity_name, ErrorMesage_Severity_value)
	proto.RegisterType((*ErrorMesage)(nil), "pplogger.ErrorMesage")
	proto.RegisterType((*Response)(nil), "pplogger.Response")
}

func init() { proto.RegisterFile("logger-service.proto", fileDescriptor_1484f153346fa394) }

var fileDescriptor_1484f153346fa394 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xd5, 0xb6, 0xdb, 0x29, 0x4a, 0x18, 0x2a, 0x2c, 0x3d, 0x48, 0xc8, 0xa9, 0x17,
	0xf7, 0x50, 0x0f, 0x82, 0xb7, 0x1c, 0xe2, 0x1f, 0x88, 0x3d, 0x6c, 0x44, 0xcf, 0x5a, 0xc6, 0x10,
	0xa8, 0xd9, 0x65, 0x36, 0x16, 0xfa, 0x11, 0xfd, 0x56, 0xd2, 0x64, 0x53, 0x3d, 0x78, 0x7c, 0x33,
	0x3f, 0xe6, 0xbd, 0x37, 0x30, 0xdf, 0xda, 0xb2, 0x24, 0xbe, 0xf2, 0xc4, 0xbb, 0x6a, 0x43, 0xda,
	0xb1, 0x6d, 0x2c, 0x4a, 0xe7, 0xba, 0x79, 0xf2, 0x2d, 0x60, 0x96, 0x31, 0x5b, 0x7e, 0x22, 0xff,
	0x56, 0x12, 0x2a, 0x98, 0x04, 0x54, 0x89, 0x58, 0x2c, 0xa7, 0xa6, 0x97, 0xb8, 0x00, 0xf9, 0xf1,
	0x55, 0x6f, 0x9a, 0xca, 0xd6, 0x6a, 0xd8, 0xae, 0x8e, 0x1a, 0x6f, 0x41, 0x7a, 0xda, 0x11, 0x57,
	0xcd, 0x5e, 0x9d, 0xc4, 0x62, 0x79, 0xbe, 0xba, 0xd4, 0xbd, 0x85, 0xfe, 0x73, 0x5e, 0x17, 0x81,
	0x32, 0x47, 0xfe, 0xe0, 0xf8, 0x49, 0xfe, 0xb0, 0x55, 0xa7, 0x9d, 0x63, 0x90, 0x89, 0x06, 0xd9,
	0xf3, 0x38, 0x85, 0xd1, 0x5d, 0xfa, 0x9c, 0xe6, 0xd1, 0x00, 0x01, 0xc6, 0x45, 0xf6, 0x92, 0x99,
	0x2c, 0x12, 0x38, 0x83, 0xc9, 0x6b, 0x6a, 0xd6, 0x8f, 0xeb, 0xfb, 0x68, 0x98, 0xc4, 0x20, 0x0d,
	0x79, 0x67, 0x6b, 0x4f, 0x38, 0x87, 0x11, 0x93, 0xdb, 0xee, 0x43, 0x8b, 0x4e, 0xac, 0x1e, 0xe0,
	0x2c, 0x6f, 0x43, 0x15, 0xa1, 0xd4, 0x0d, 0xc8, 0xdc, 0x96, 0x6d, 0x42, 0xbc, 0xf8, 0x37, 0xf2,
	0x02, 0x7f, 0xc7, 0xfd, 0xf5, 0x64, 0xf0, 0x3e, 0x6e, 0x1f, 0x79, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x99, 0xc9, 0xc4, 0x60, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerServiceClient is the client API for LoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerServiceClient interface {
	LogError(ctx context.Context, in *ErrorMesage, opts ...grpc.CallOption) (*Response, error)
}

type loggerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggerServiceClient(cc *grpc.ClientConn) LoggerServiceClient {
	return &loggerServiceClient{cc}
}

func (c *loggerServiceClient) LogError(ctx context.Context, in *ErrorMesage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pplogger.LoggerService/LogError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServiceServer is the server API for LoggerService service.
type LoggerServiceServer interface {
	LogError(context.Context, *ErrorMesage) (*Response, error)
}

// UnimplementedLoggerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServiceServer struct {
}

func (*UnimplementedLoggerServiceServer) LogError(ctx context.Context, req *ErrorMesage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogError not implemented")
}

func RegisterLoggerServiceServer(s *grpc.Server, srv LoggerServiceServer) {
	s.RegisterService(&_LoggerService_serviceDesc, srv)
}

func _LoggerService_LogError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorMesage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServiceServer).LogError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pplogger.LoggerService/LogError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServiceServer).LogError(ctx, req.(*ErrorMesage))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pplogger.LoggerService",
	HandlerType: (*LoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogError",
			Handler:    _LoggerService_LogError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger-service.proto",
}
